name: Sync ADO Issue

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to sync'
        required: true
        default: '1'
  issues:
    types: [labeled, closed, reopened]

permissions:
  issues: write
  id-token: write
  contents: read

jobs:
  alert:
    runs-on: windows-latest
    name: Syncing to Azure DevOps
    steps:
    - name: Sync to ADO
      uses: chetanpandey1266/github-actions-issue-to-work-item@simple-sync-azurecli
      env:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
      with:
        label: 'tracked'
        ado_organization: 'microsoft'
        ado_project: 'Edge'
        ado_area_path: 'Edge\Web Experience\WebView2'
        ado_tags: 'WV2_GitHub'
        ado_gh_closed_tag: 'WV2_GitHub_Closed'
